Update libbpf
netdata/kernel-collector pull request #255
Opened 2021-08-31 00:03 UTC by thiagoftsm

More details after #252 to be merged.

2021-09-07 09:49 UTC, vlvkobal commented
> This PR is also adding libbpf as submodule
Why did you decide to use a submodule. We had a discussion with you a couple of months before and we decided that using submodules is a bad idea. Has anything changed since then?

2021-09-07 14:18 UTC, thiagoftsm commented
> > This PR is also adding libbpf as submodule
> 
> Why did you decide to use a submodule. We had a discussion with you a couple of months before and we decided that using submodules is a bad idea. Has anything changed since then?

Yes @vlvkobal the new features we will bring, and the fact that `libbpf` is having many changes these days, the new release they will make will be named `1.0`, because it will break compatibility with old versions. Among the features and changes they made that forced us to move in this direction are:

-  They have more than one header now, and we expect more headers will be added.
-   To create binaries that do not have relationship with kernels (`CO-RE`), `libbpf` will be necessary.

2021-09-15 06:16 UTC, vlvkobal submitted a review, later dismissed

2021-09-15 23:33 UTC, UmanShahzad requested changes

2021-09-15 23:33 UTC, UmanShahzad commented on kernel/Makefile
> +	      mount \
Are these additions to the `NETDATA_APPS` list being repeated on purpose?

2021-09-15 23:33 UTC, UmanShahzad commented on kernel/btrfs_kern.c
> +#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,15,0))
This check is happening within the above check of `code > 5.4.14`, so it will always be false, right? So in all of these newer table declarations, we can expect per-CPU hashes to always be available, and don't need a separate check.

2021-09-16 00:44 UTC, thiagoftsm commented on kernel/Makefile
> +	      mount \
This was during rebase :eyes: . I fixed with last commits.

2021-09-16 00:46 UTC, thiagoftsm commented on kernel/btrfs_kern.c
> +#if (LINUX_VERSION_CODE < KERNEL_VERSION(4,15,0))
I copied and pasted changing only the declaration to simplify comparison, but I agree that we can remove it, and I brought a commit for this.

2021-09-16 00:55 UTC, UmanShahzad approved these changes

2021-09-16 05:48 UTC, vlvkobal approved these changes

2021-09-16 13:45 UTC, merged